shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - undici@5.29.0
catalogs:
  build:
    rolldown: 1.0.0-rc.3
  dev:
    '@actions/core': ^3.0.0
    '@antfu/eslint-config': ^7.4.2
    eslint: ^10.0.0
    nitro: 3.0.1-alpha.2
    typescript: ^5.9.3
    wait-on: ^9.0.3
    wrangler: ^4.64.0
  lib:
    '@upstash/redis': ^1.36.2
    aws4fetch: ^1.0.20
    ioredis: ^5.9.2
    skland-kit: ^0.3.4
    statocysts: ^0.10.3
    unctx: ^2.5.0
    unstorage: ^2.0.0-alpha.5
  types:
    '@types/node': ^25.2.2
