name: attendance

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:
  workflow_call:
    secrets:
      SKLAND_TOKEN:
        required: true
      SERVERCHAN_SENDKEY:
        required: false
      BARK_URL:
        required: false
      MESSAGE_PUSHER_URL:
        required: false
      MAX_RETRIES:
        required: false
    inputs:
      repository:
        description: 'The repository to run the workflow on'
        default: 'enpitsuLin/skland-daily-attendance'
        required: false
        type: string

jobs:
  attendance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository || github.repository }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run daily attendance
        run: pnpm -C "./apps/node" start
        env:
          SKLAND_TOKEN: ${{ secrets.SKLAND_TOKEN }}
          SERVERCHAN_SENDKEY: ${{ secrets.SERVERCHAN_SENDKEY }}
          BARK_URL: ${{ secrets.BARK_URL }}
          MESSAGE_PUSHER_URL: ${{ secrets.MESSAGE_PUSHER_URL }}
          MAX_RETRIES: ${{ secrets.MAX_RETRIES }}
